framework:
  messenger:
    failure_transport: failed

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: 'doctrine://default?queue_name=failed'
      async_priority_high:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queue_name: high
      async_priority_low:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queue_name: low

    routing:

