security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      entry_point: App\Security\LoginFormAuthenticator
      custom_authenticator:
        - App\Security\LoginFormAuthenticator
  
      logout:
        path: app_logout
        target: app_login
        invalidate_session: true
        delete_cookies:
          remember_me: { path: / }
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800  # 7 days in seconds
        path: /
        secure: true  # Adjust based on your site's HTTPS configuration
        name: SECURITY_DEMO

  access_control:
  - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/nom, roles: ROLE_SUPER_ADMIN }
  - { path: ^/salle, roles: ROLE_SUPER_ADMIN }
  - { path: ^/client, roles: ROLE_CLIENT }
  - { path: ^/transcribe, roles: ROLE_CLIENT }
  - { path: ^/reclamation/new, roles: ROLE_CLIENT }
  - { path: ^/reclamation, roles: ROLE_SUPER_ADMIN }
  - { path: ^/reponse, roles: ROLE_SUPER_ADMIN }
    # Additional access control rules as needed

    # Ensure login and logout paths are accessible to all
    # - { path: ^/login, roles: ROLE_USER }
    # - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
