#index:
#    path: /
#    controller: App\Controller\DefaultController::index
reclamation_search:
  path: /search
  controller: App\Controller\ReclamationController::search

reponse_search:
  path: /search1
  controller: App\Controller\ReponseController::search1
