#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_search:
  path: /search
  controller: App\Controller\UserController::search

client_search1:
  path: /search1
  controller: App\Controller\UserController::search1

