#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#generate_qr_code:
#  path: /generate_qr_code/{ticketId}
#  controller: App\Controller\QRCodeController::generateQRCode
#  methods: ['GET']


ticket_search:
    path: /search
    controller: App\Controller\TicketController::search


evenement_search1:
    path: /search1
    controller: App\Controller\EvenementController::search1