#index:
#    path: /
#    controller: App\Controller\DefaultController::index
reclamation_search:
  path: /search
  controller: App\Controller\ReclamationController::search

reponse_search:
  path: /search1
  controller: App\Controller\ReponseController::search1
activite_search2:
  path: /search2
  controller: App\Controller\ActiviteController::search2

salle_search3:
  path: /search3
  controller: App\Controller\SalleController::search3

ticket_search:
  path: /search
  controller: App\Controller\TicketController::search


evenement_search1:
  path: /search1
  controller: App\Controller\EvenementController::search1