#index:
#    path: /
#    controller: App\Controller\DefaultController::index
activite_search:
  path: /search
  controller: App\Controller\ActiviteController::search

salle_search1:
  path: /search1
  controller: App\Controller\SalleController::search1
